import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/header/Header";
import Footer from "./_components/footer/Footer";
// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
// });
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: {
    template: "%s | Rose",
    default: "Rose",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-heading  antialiased`}>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
