import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "../components/layout/footer";
import Providers from "@/context";
import FormModal from "@/components/custom/auth/FormModal";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import LoadingSpinner from "@/components/common/spinner/LoadingSpinner";
//======================================= font ===================================
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
//====================================== metadata ================================
export const metadata: Metadata = {
  title: {
    template: "%s | Rose",
    default: "Rose",
  },
  description: "Generated by create next app",
};
//===============================================================================
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<LoadingSpinner />}>
      <html lang="en">
        <body className={`${inter.className} text-heading  antialiased `}>
          <Providers>
            <Header />
            <main className="mt-[110px] mt-[140px]">{children}</main>

            <FormModal />
            <Toaster
              toastOptions={{
                classNames: {
                  toast:
                    "   !z-[9999999999999999999999999999999999999999999999999999999999999999999]",
                },
              }}
            />

            <Footer />
          </Providers>
        </body>
      </html>
    </Suspense>
  );
}
